### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by lensh** [woai3c/i18n-replace#2]
我在vue项目配置完后，用不了，你可以提供一个vue项目写的demo吗。

**Comment by woai3c** [comment]
测试跑得通吗

**Comment by woai3c** [comment]
> 我在vue项目配置完后，用不了，你可以提供一个vue项目写的demo吗。

我刚才试了一下，可以跑。你是否用的全局安装，安装后测试是否能跑通？

**Comment by lensh** [comment]
我在vue项目里面用不了

**Comment by woai3c** [comment]
报错信息发一下

**Comment by lensh** [comment]
没有报错，就是没有把中文翻译成英文。。测试项目地址：https://github.com/lensh/test-i18n-replace  

看能不能加个V聊

**Comment by woai3c** [comment]
> 没有报错，就是没有把中文翻译成英文。。测试项目地址：https://github.com/lensh/test-i18n-replace
> 
> 看能不能加个V聊

你这是配置项有问题，把配置文件改成这样：
```js
module.exports = {
    appid: '20201209000642959', // 百度翻译 appid
    key: 'T_kK46X3KeJfbyzY8nYB', // 百度翻译密钥
    translation: true, // 是否需要自动翻译中文
}
```
就可以了。
![image](https://user-images.githubusercontent.com/22117876/101904322-a0268180-3bf0-11eb-9c0d-44aa482cf0de.png)
![image](https://user-images.githubusercontent.com/22117876/101904339-a6b4f900-3bf0-11eb-9684-cc4bf3129fc4.png)

**Comment by lensh** [comment]
![image](https://user-images.githubusercontent.com/20356263/102684491-04aa9780-4214-11eb-8f0d-1cee6945241d.png)

翻译完后。打开页面，报了这个错

**Comment by woai3c** [comment]
你没装 vue-in18 插件吧

**Comment by lensh** [comment]
现在可以了，不过执行rep命令，只能翻译一种语言，这里to只能配置一种语言，能配置多种吗？
![image](https://user-images.githubusercontent.com/20356263/102735358-26735e00-437d-11eb-80df-f6a60c5e9d89.png)

**Comment by woai3c** [comment]
> 现在可以了，不过执行rep命令，只能翻译一种语言，这里to只能配置一种语言，能配置多种吗？
> ![image](https://user-images.githubusercontent.com/20356263/102735358-26735e00-437d-11eb-80df-f6a60c5e9d89.png)

可以看，看一下百度翻译的 API 文档。根据文档配置目标语言。
