### ISSUE TITLE
对于一些不在标签符号内的处理存在缺陷，不需要花括号了

### ISSUE THREAD

**Issue by hotFixMan** [woai3c/i18n-replace#4]
对于一些不在标签符号内的处理存在缺陷，不需要花括号了
![image](https://user-images.githubusercontent.com/45447021/120760085-47ec8e80-c546-11eb-9114-71e5c48ccd6b.png)

**Comment by hotFixMan** [comment]
![image](https://user-images.githubusercontent.com/45447021/120760447-b5002400-c546-11eb-951a-c80b2f38fa97.png)

**Comment by woai3c** [comment]
第一张图可以提供一个最小可复现的代码示例吗？第二张图你是使用中文作为翻译插件的 key 吗，目前没有考虑这种情况。
