### ISSUE TITLE
如何使用没说呀

### ISSUE THREAD

**Issue by 2395000206** [woai3c/i18n-replace#5]

**Comment by 2395000206** [comment]
不知道用

**Comment by woai3c** [comment]
兄弟看看 test 目录，有测试用例

**Comment by 2395000206** [comment]
vue可以使用这个吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 中午1:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [woai3c/i18n-replace] 如何使用没说呀 (#5)





 
兄弟看看 test 目录，有测试用例
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by woai3c** [comment]
> vue可以使用这个吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年9月16日(星期四) 中午1:50 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [woai3c/i18n-replace] 如何使用没说呀 (#5) 兄弟看看 test 目录，有测试用例 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

可以的

**Comment by 2395000206** [comment]
如何使用我按要求下载了也配置了appid

**Comment by 2395000206** [comment]
我想问一下这个不会是，我全局安装然后自己去引入vue文件把他编译后，最后使用吧

**Comment by 2395000206** [comment]
能出一个案例吗，我看了下test还是不知道怎么使用

**Comment by woai3c** [comment]
![image](https://user-images.githubusercontent.com/22117876/133560874-428f9ec1-f2d2-480f-be09-80f094a0ca52.png)
