### ISSUE TITLE
属性为中文时会出问题

### ISSUE THREAD

**Issue by 2395000206** [woai3c/i18n-replace#6]
![image](https://user-images.githubusercontent.com/58016208/133567947-74c85e8f-3ae2-4caa-8fb8-1702e9b302b4.png)

**Comment by 2395000206** [comment]
![image](https://user-images.githubusercontent.com/58016208/133568168-0b2de0f7-a753-4252-925e-b4cfbe5dcee1.png)

**Comment by 2395000206** [comment]
这种问题要如何解决

**Comment by woai3c** [comment]
https://github.com/woai3c/i18n-replace/issues/7
