### ISSUE TITLE
转换后存在的问题

### ISSUE THREAD

**Issue by 2395000206** [woai3c/i18n-replace#7]
![image](https://user-images.githubusercontent.com/58016208/133567947-74c85e8f-3ae2-4caa-8fb8-1702e9b302b4.png)
![image](https://user-images.githubusercontent.com/58016208/133570474-588a5141-0bc9-4de1-a4e1-ac2e100ebf44.png)

**Comment by woai3c** [comment]
目前的转换方案有问题，后续会考虑用新的方法来转换。即先将代码转换为 ast 节点，然后对比 ast 上的内容来转换。

**Comment by dwwwd1234** [comment]
写入mapFile默认文件一直报错
