### ISSUE TITLE
写入默认mapFile报错

### ISSUE THREAD

**Issue by dwwwd1234** [woai3c/i18n-replace#8]
写入默认mapFile报错
![1637295995(1)](https://user-images.githubusercontent.com/94664823/142564802-51addd07-fc44-4d3d-af00-a113c011f6f2.png)
![1637296016(1)](https://user-images.githubusercontent.com/94664823/142564821-9139363b-3f00-4803-beeb-b8b3b8ec2592.png)

**Comment by woai3c** [comment]
看一下报错信息，提示没有找到文件 
![image](https://user-images.githubusercontent.com/22117876/142748293-8caa7280-940e-482f-9e76-5f21d7ff6f65.png)

把目录换成英文试试。

**Comment by woai3c** [comment]
太久没响应，关闭问题。
