### ISSUE TITLE
M1 Mac 执行无反应

### ISSUE THREAD

**Issue by 41369ly** [woai3c/i18n-replace#9]
<img width="816" alt="image" src="https://user-images.githubusercontent.com/51309038/160230325-d61d0146-afc4-4e4f-9878-b7c7ee1a62d9.png">
<img width="581" alt="image" src="https://user-images.githubusercontent.com/51309038/160230348-5f244a0d-6da9-4b17-aff6-3ac578d10f69.png">
图一为反复执行后截图，图二是安装成功的截图

**Comment by 41369ly** [comment]
> <img alt="图片" width="816" src="https://user-images.githubusercontent.com/51309038/160230325-d61d0146-afc4-4e4f-9878-b7c7ee1a62d9.png">
> 
> <img alt="图片" width="581" src="https://user-images.githubusercontent.com/51309038/160230348-5f244a0d-6da9-4b17-aff6-3ac578d10f69.png">
> 
> 图一为执行重复后截图，图二是安装成功的截图



> <img alt="图片" width="816" src="https://user-images.githubusercontent.com/51309038/160230325-d61d0146-afc4-4e4f-9878-b7c7ee1a62d9.png">
> 
> <img alt="图片" width="581" src="https://user-images.githubusercontent.com/51309038/160230348-5f244a0d-6da9-4b17-aff6-3ac578d10f69.png">
> 
> 图一为执行重复后截图，图二是安装成功的截图

配置问题。。。。需要配置include，我还以为默认扫描所有文件夹

**Comment by woai3c** [comment]
include 可以不配置，需要配置 entry，如果不配置 entry 则默认扫描的是 src 目录。
